
package jaxws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterSoapSAI", targetNamespace = "http://jaxws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterSoapSAI {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saiRam", targetNamespace = "http://jaxws/", className = "jaxws.SaiRam")
    @ResponseWrapper(localName = "saiRamResponse", targetNamespace = "http://jaxws/", className = "jaxws.SaiRamResponse")
    @Action(input = "http://jaxws/InterSoapSAI/saiRamRequest", output = "http://jaxws/InterSoapSAI/saiRamResponse")
    public String saiRam();

}
